package(default_visibility = ["//visibility:public"])

cc_proto_library(
    name = "uhnder_cc_proto",
    deps = [
        ":uhnder_proto",
    ],
)

proto_library(
    name = "uhnder_proto",
    srcs = ["uhnder.proto"],
)


