load("//tools:cpplint.bzl", "cpplint")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "joystick_util",
    srcs = [],
    hdrs = [
        "macros.h",
    ],
)

cpplint()
